name: Video Factory

on:
  schedule:
    # Runs at 08:00 UTC every day (Adjust to your morning)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate-video:
    # SWITCHING BACK TO LATEST FOR SPEED
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # Force permissions for text generation
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Libraries
        run: |
          # We use latest Ubuntu, but force OLD Pillow to prevent crashes
          pip install Pillow==9.5.0
          pip install moviepy==1.0.3 gTTS requests decorator==4.4.2 imageio tqdm numpy

      - name: Run Video Generator
        run: python maker.py

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: viral-short
          path: output.mp4
