name: Video Factory

on:
  workflow_dispatch: # Allows you to click a button to generate a video

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install System Dependencies (ImageMagick)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # Fix for ImageMagick policy (allows text processing)
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Video Generator
        run: python maker.py

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: viral-short
          path: output.mp4
