name: Video Factory

on:
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-20.04 # We use an older, more stable Linux version for MoviePy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # FORCE PERMISSIONS FOR TEXT GENERATION
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Libraries
        run: |
          pip install moviepy==1.0.3 gTTS requests decorator==4.4.2 imageio tqdm numpy

      - name: Run Video Generator
        run: python maker.py

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: viral-short
          path: output.mp4
